### ISSUE TITLE
kcc doesn't handle sigjmp_buf

### ISSUE THREAD

**Issue by shijieg2** [kframework/c-semantics#320]
You can reproduce the problem by doing
```
git clone https://github.com/Lycbel/cs510Files
cd cs510Files/miniInput_curl
# the script lists the kcc version that was tested
./bug_report_curl.sh
```

**Comment by chathhorn** [comment]
I believe these cases should work with `kcc -std=gnu11` -- `kcc` assumes `-std=c11` otherwise. We'll likely eventually want to make `-std=gnu11` the default, but our support of GNU features isn't complete enough yet (and we want to discourage use of such features by e.g. build systems that use autoconf).
